name: Releases
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for Shared Runner
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
      - uses: ncipollo/release-action@v1
        name: Create Release
        with:
          artifacts: "target/folder-agent.hpi"
