on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 for Shared Runner
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build and Publish to GitHub Packages Apache Maven
      run: mvn -B deploy --file pom.xml -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
