on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for Shared Runner
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
      - name: Upload HPI
        uses: actions/upload-artifact@v4
        with:
          name: folder-agent
          path: target/folder-agent.hpi